-- Sign-up and business setup: user_profile kept in sync with auth.users, business
-- trade / tax status / logo, an idempotent setup_business() RPC, and a private
-- Storage bucket for business assets (logos).

create type public.business_trade as enum (
  'electrician', 'plumber', 'hvac', 'handyman', 'locksmith', 'painter', 'other'
);
-- Israeli tax registration: עוסק פטור / עוסק מורשה / חברה בע"מ.
create type public.tax_status as enum ('osek_patur', 'osek_murshe', 'company');

alter table public.business
  add column trade public.business_trade,
  add column tax_status public.tax_status,
  -- Object path inside the business-assets bucket: '<business_id>/logo-<uuid>.<ext>'.
  add column logo_path text check (char_length(logo_path) between 1 and 1024);

-- ---------------------------------------------------------------------------
-- user_profile is created for every new auth user and follows phone changes.
-- ---------------------------------------------------------------------------
create function app.sync_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  -- GoTrue stores phones as digits without '+'; keep only valid E.164.
  v_phone text := case when new.phone ~ '^[1-9][0-9]{1,14}$' then '+' || new.phone end;
begin
  insert into public.user_profile (id, phone_e164)
  values (new.id, v_phone)
  on conflict (id) do update set phone_e164 = excluded.phone_e164;
  return new;
end;
$$;

revoke execute on function app.sync_user_profile() from public, anon, authenticated;

create trigger sync_user_profile_on_insert after insert on auth.users
  for each row execute function app.sync_user_profile();
create trigger sync_user_profile_on_phone_change after update of phone on auth.users
  for each row when (old.phone is distinct from new.phone)
  execute function app.sync_user_profile();

-- Backfill users created before this migration.
insert into public.user_profile (id, phone_e164)
select u.id, case when u.phone ~ '^[1-9][0-9]{1,14}$' then '+' || u.phone end
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Business creation. Both RPCs share app.insert_business(), which creates the
-- business, its settings and the OWNER membership in one transaction.
-- ---------------------------------------------------------------------------
create function app.insert_business(
  p_business_id uuid,
  p_owner_id uuid,
  p_name text,
  p_trade public.business_trade,
  p_tax_status public.tax_status
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.business (id, name, trade, tax_status)
  values (p_business_id, p_name, p_trade, p_tax_status);
  insert into public.business_settings (business_id) values (p_business_id);
  insert into public.business_member (business_id, user_id, role, status)
  values (p_business_id, p_owner_id, 'OWNER', 'active');
  return p_business_id;
end;
$$;

revoke execute on function app.insert_business(uuid, uuid, text, public.business_trade, public.tax_status)
  from public, anon, authenticated;

-- Same signature and behaviour as before; now delegates to app.insert_business().
create or replace function public.create_business(p_name text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;
  return app.insert_business(gen_random_uuid(), auth.uid(), p_name, null, null);
end;
$$;

-- Business setup from onboarding. p_business_id is generated by the client, so
-- a retried request (double tap, flaky network) returns the same business
-- instead of creating a second one.
create function public.setup_business(
  p_business_id uuid,
  p_name text,
  p_trade public.business_trade,
  p_tax_status public.tax_status
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'not authenticated' using errcode = '28000';
  end if;

  if exists (select 1 from public.business where id = p_business_id) then
    if app.has_role(p_business_id, '{OWNER}') then
      return p_business_id;
    end if;
    raise exception 'business id already in use' using errcode = '42501';
  end if;

  return app.insert_business(p_business_id, v_user_id, p_name, p_trade, p_tax_status);
end;
$$;

revoke execute on function public.setup_business(uuid, text, public.business_trade, public.tax_status)
  from public, anon;
grant execute on function public.setup_business(uuid, text, public.business_trade, public.tax_status)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Storage: private bucket for business assets. Objects live under
-- '<business_id>/...'; members read, OWNER/ADMIN write.
-- ---------------------------------------------------------------------------
create function app.try_uuid(p_value text)
returns uuid
language plpgsql
immutable
set search_path = ''
as $$
begin
  return p_value::uuid;
exception when invalid_text_representation then
  return null;
end;
$$;

grant execute on function app.try_uuid(text) to authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('business-assets', 'business-assets', false, 2097152,
        array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do nothing;

create policy business_assets_select on storage.objects for select to authenticated
  using (bucket_id = 'business-assets'
         and app.is_member(app.try_uuid((storage.foldername(name))[1])));
create policy business_assets_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'business-assets'
              and app.has_role(app.try_uuid((storage.foldername(name))[1]), '{OWNER,ADMIN}'));
create policy business_assets_update on storage.objects for update to authenticated
  using (bucket_id = 'business-assets'
         and app.has_role(app.try_uuid((storage.foldername(name))[1]), '{OWNER,ADMIN}'))
  with check (bucket_id = 'business-assets'
              and app.has_role(app.try_uuid((storage.foldername(name))[1]), '{OWNER,ADMIN}'));
create policy business_assets_delete on storage.objects for delete to authenticated
  using (bucket_id = 'business-assets'
         and app.has_role(app.try_uuid((storage.foldername(name))[1]), '{OWNER,ADMIN}'));
